### ISSUE TITLE
add option to fail if unzip cannot find any files to unzip

### ISSUE THREAD

**Issue by Michael-Gannon** [twolfson/grunt-zip#24]
If the configuration specified cannot resolve a file(s) to unzip the output is successful and     'File "' + this.file.dest + '" created.' is printed, this is not true if the files were not found.

**Comment by bladerunner2020** [comment]
> I don't think it should fail, we just need to update the wording. The user will read that and realize something needs correction. This also seems to be grunt convention:
> 
> https://github.com/gruntjs/grunt-contrib-copy/blob/v0.5.0/tasks/copy.js#L35-L71

grunt-contrib-copy has an option `nonull` - if this option is true and file not found grunt fails.
would be great to have the same behaviour to grunt-zip. 

flag --verbose does help, but still would be nice to have `nonull` flag in grunt-zip.

**Comment by twolfson** [comment]
@bladerunner2020 Due to reduced popularity of `grunt` and personal priorities with other tasks, I'm not actively adding features to this repo. I'll happily accept a PR on that though
