### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by mcfarljw** [twolfson/grunt-zip#32]
I'm having some troubles getting a larger files to unzip on my machine (Windows 8.1). It keeps throwing the exit code listed in the issue title. Here is one of the files I'm trying to unzip:

https://download.01.org/crosswalk/releases/crosswalk/android/beta/8.37.189.2/arm/crosswalk-cordova-8.37.189.2-arm.zip

I recall this working a month or so ago, but I'm not entirely sure what to make of the exit code. Any thoughts?

**Comment by paperplane123** [comment]
我也遇到了同样的问题，请问您最后是如何解决的

**Comment by twolfson** [comment]
@paperplane123 What version of Node.js are you using?

**Comment by paperplane123** [comment]
oh.no. I find this problem in python

**Comment by twolfson** [comment]
Ah, sorry. I can't help you there -- this issue and repo are specific to `grunt-zip` in Node.js =/

**Comment by paperplane123** [comment]
I Know . And still very grateful

**Comment by sunshinelover** [comment]
@paperplane123 解决了吗？遇到这个问题+1

**Comment by paperplane123** [comment]
@sunshinelover 解决了，好像是我代码本身的问题，你也在用python?

**Comment by sunshinelover** [comment]
@paperplane123 嗯嗯，那可能我代码也有问题==

**Comment by paperplane123** [comment]
慢慢该吧，加油

**Comment by sunshinelover** [comment]
好滴，谢谢！
