### ISSUE TITLE
'src' of undefined

### ISSUE THREAD

**Issue by harpreetkhalsagtbit** [twolfson/grunt-zip#34]
I am using this method
```js
    unzip: {
      'location/to/extract/files/': 'file/to/extract.zip'
    }
```
defined in your **readme.md** but i am getting this error

`'src' of undefined`

then I found [this](http://twolfson.com/2014-01-19-low-tech-dependency-management-via-grunt-tasks) after googling and it works

```js
renameZipToDocx: {
    src: '@@All Siri Guru Granth Sahib in Gurmukhi, without Index.zip',
    dest: '@@All Siri Guru Granth Sahib in Gurmukhi, without Index.docx'
}
```
please check this issue....

**Comment by twolfson** [comment]
It sounds like a path is wrong, can you try running `grunt unzip --verbose`? Alternative `src/dest` formats can be found in the README:

https://github.com/twolfson/grunt-zip#unzip-1
