### ISSUE TITLE
Build currently failing

### ISSUE THREAD

**Issue by TheSavior** [twolfson/grunt-zip#38]
The build is currently failing on master on Travis.

**Comment by twolfson** [comment]
Ah, damn. Sorry for the slow reply. Thanks for the heads up. I will see what we can do.

**Comment by twolfson** [comment]
We have loosened up the test suite and updated our `node` version support (now `>=0.10.0`) to get it back to green. Thanks again for the heads up =)

**Comment by TheSavior** [comment]
Awesome. As a heads up, iojs was merged back into nodejs and the current version of node is 4.0.0. If you only specify `node` in your travis file you will be using that version. I'd recommend specifying that instead of `iojs`.

**Comment by twolfson** [comment]
Yep, I wanted to lock to `4.0` but it doesn't seem to be in Travis CI yet. The `iojs` lock is versionless convention I have been using since `iojs` had releases so frequently.

**Comment by TheSavior** [comment]
4.0.0 is definitely in Travis, but I would recommend locking to `4` instead of `4.0` since they are trying to follow semver now. `iojs` I believe will never have a new version on travis, and `node` is the new versionless one (which is probably good to have just to know how forwards compatible you are.

**Comment by twolfson** [comment]
Ah, fair enough with respect to semver.

With respect to using `iojs`, I think I was making an assumption about Travis CI. I occasionally see a blog post about them upgrading their environment support so I was thinking that one of those would exist for `4.0.0` as well:

http://docs.travis-ci.com/user/build-environment-updates/

**Comment by TheSavior** [comment]
Interesting. It looks like that link hasn't been updated in a while. Travis uses nvm so any version there is available on Jenkins including 4.0.0: http://docs.travis-ci.com/user/ci-environment/#Node.js-VM-images
