### ISSUE TITLE
[wrong issue - delete]

### ISSUE THREAD

**Issue by eliasjnior** [twolfson/grunt-zip#42]
wrong issue - delete

**Comment by twolfson** [comment]
I don't understand the question. Can you provide more context?

**Comment by eliasjnior** [comment]
@twolfson supose that I run "grunt c" to compress my theme. This command will generate a zip file "odin.zip" in the root of the theme folder, right?

But this ZIP isn't a instalable zip file for WordPress themes. I cannot upload the ZIP in the WP Dashboard and install the theme, because the zip structure need to be:

- theme_name
   - index.php
   - style.css

Another thing is that the ZIP file generated don't have assets/sass/*, assets/libs/*, assets/bootstrap/*.

If I send this ZIP for my client, for example, and they want to change CSS, it' will be a problem because the ZIP file just contains style.css compressed, not the SASS files and then compress all again.

**Comment by eliasjnior** [comment]
Wow, I just opened a issue in the wrong repository hahahhahahahahah
sorry!

**Comment by twolfson** [comment]
Okie doke, closing issue
