### ISSUE TITLE
Issue: Unzip archives which contains large files

### ISSUE THREAD

**Issue by Simona-A-R** [twolfson/grunt-zip#45]
I have a zip archive which contains several files and one of this file has 421MB size.
Grunt unzip throws the following error:
`Warning: Invalid string length Use --force to continue.`

Example:
```
unzip: {
    src: "dir/*.zip",
    dest: "dir"
}
```

The archive doesn't seem to be corrupt and it works if I used 7z for example.
I can fix this issue by setting `checkCRC32: false` but I don't know why it is needed.
P.S I can't provide the archive since it contains client information.

**Comment by twolfson** [comment]
Would it be possible for me to get a copy of the file? It will be hard for me to debug it otherwise =/

**Comment by Simona-A-R** [comment]
Sorry, but unfortunately I can't provide you that file, it is confidential. 
I know it is hard for you to debug, you can try with different types of files and with larger size than 400MB, maybe you can find out something. Thank you!

**Comment by twolfson** [comment]
Maybe you can generate another ZIP file via the same confidential process and see if it generates the same error? Based on your CRC32 patch, I have a feeling it's specific to the file

**Comment by Simona-A-R** [comment]
I have more than one archive with at least one file larger than 400MB inside and I got the same issue. I'll continue to investigate on my side for those specific files.

**Comment by twolfson** [comment]
Cool, I'm going to close this issue for now since it's blocked on my side. We can re-open if we have something to iterate on
