### ISSUE TITLE
Multiple zips?

### ISSUE THREAD

**Issue by r14n** [twolfson/grunt-zip#46]
Is it possible to have this task run twice with different options to generate two distinct zip files?  If so, how would I do that?

**Comment by twolfson** [comment]
In Grunt, that is best achieved by defining 2 different tasks and defining a command to run both of them:

```js
zip: {
  zip1: {src, dest},
  zip2: {src, dest}
}

// Run all `zip` tasks via `grunt zip`

// Or define a custom task (e.g. `grunt zip-custom`)
grunt.registerTask('zip-custom', ['zip:zip1', 'zip:zip2']);
```

**Comment by r14n** [comment]
thank you
