### ISSUE TITLE
Unneccesary files 

### ISSUE THREAD

**Issue by AliOsseili** [twolfson/grunt-zip#51]
Fixed the issue here: https://github.com/twolfson/grunt-zip/issues/50 by using the routers skipping files option, but now when I open my zip it has too many unnecessary folders, here is what it should look like:
enhancedfeedleft-win32-x64(time).zip
 - all the stuff inside that I want zipped

here is what it actually looks like

enhancedFeedLeft-win32-x64(time).zip
-build
   -enhancedfeedleft...
      - build
          - enhancedfeedleft...
             - all the stuff I want zipped

any ideas on how to fix that, here is what my grunt zip task looks like: 

'zip': {
            'skip-files': {
                router: function (filepath) {
                    var extname = path.extname(filepath)
                        if (extname === '.zip') {
                            return null;
                        } else {
                            return 'build/enhancedFeedLeft' + '-' + os_platform + '-' + arch_model + '/'+filepath;
                        }
                },
                src: ['build/enhancedFeedLeft' + '-' + os_platform + '-' + arch_model + '/**'],
                dest: 'BuildZip/enhancedFeedLeft' + '-' + os_platform + '-' + arch_model + '-' + TimeNow + '.zip'
            }
        }

**Comment by twolfson** [comment]
I think `filepath` is the full filepath so you're doubly nesting the filepath. Try out:

```js
'zip': {
'skip-files': {
router: function (filepath) {
var extname = path.extname(filepath)
if (extname === '.zip') {
return null;
} else {
return filepath;
}
},
src: ['build/enhancedFeedLeft' + '-' + os_platform + '-' + arch_model + '/**'],
dest: 'BuildZip/enhancedFeedLeft' + '-' + os_platform + '-' + arch_model + '-' + TimeNow + '.zip'
}
}
```

**Comment by AliOsseili** [comment]
now its nesting it once, is there a way to avoid doing that? I just want the zip to contain what I want zipped instead of having:

electronfeedleft.... .zip
-build
-electronfeedleft
- all that I want zipped

I'd like 

electronfeedleft.... .zip
-all that I wwant zipped

**Comment by twolfson** [comment]
Ahhh, I understand. Yea, using `path.basename` we can extract the root filename:

https://nodejs.org/api/path.html#path_path_basename_path_ext

```js
'zip': {
'skip-files': {
router: function (filepath) {
var extname = path.extname(filepath)
if (extname === '.zip') {
return null;
} else {
return path.basename(filepath);
}
},
src: ['build/enhancedFeedLeft' + '-' + os_platform + '-' + arch_model + '/**'],
dest: 'BuildZip/enhancedFeedLeft' + '-' + os_platform + '-' + arch_model + '-' + TimeNow + '.zip'
}
}
```

**Comment by AliOsseili** [comment]
That sort of fixes the issue, except now its broken down the files within the zip I want into their sub files and my zip in result is disorganized so now instead of my zip looking like this (I manually created this one):

<img width="1920" alt="whatiwant" src="https://user-images.githubusercontent.com/36897722/36919519-9f0da066-1e2b-11e8-9a6f-5f77b693dcc9.png">

it looks like 
<img width="1920" alt="whatidontwant" src="https://user-images.githubusercontent.com/36897722/36919627-f550e9ce-1e2b-11e8-84b7-72eea2b0584f.png">

**Comment by AliOsseili** [comment]
When I tried that it gave me even more files lol: 
What it should look like 
<img width="1920" alt="whatiwant" src="https://user-images.githubusercontent.com/36897722/36919786-7cbff0e4-1e2c-11e8-9b9a-3ac6858c58f9.png">

what it actually does 
<img width="1920" alt="whatidontwant" src="https://user-images.githubusercontent.com/36897722/36919792-829f4f46-1e2c-11e8-8230-6fd30e4207fb.png">

**Comment by twolfson** [comment]
I think your glob pattern is off. Try `**/*` instead of `**`:

```js
'zip': {
'skip-files': {
router: function (filepath) {
var extname = path.extname(filepath)
if (extname === '.zip') {
return null;
} else {
return path.basename(filepath);
}
},
src: ['build/enhancedFeedLeft' + '-' + os_platform + '-' + arch_model + '/**/*'],
dest: 'BuildZip/enhancedFeedLeft' + '-' + os_platform + '-' + arch_model + '-' + TimeNow + '.zip'
}
}
```
